name: Docker Build & Push with Cache
on: [push, pull_request]
env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner | lower }}  # 全局安全变量

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      # 步骤1: 解析动态变量（关键！）
      - name: Generate cache image name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          echo "CACHE_IMAGE=ghcr.io/${{ env.OWNER }}/$REPO_NAME:build-cache-${{ matrix.platform }}" >> $GITHUB_ENV
      
      # 步骤2: 常规步骤 (略同原流程)
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      
      # 步骤3: 构建推送（启用分平台缓存）
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}
          cache-to: type=registry,ref=${{ env.CACHE_IMAGE }},mode=max
